config/routes.rb
Rails.application.routes.draw do

  

  get 'calendar/index'

  root 'users#index'
  
  
  get 'maps' => 'maps#index'
  
  get '/courses' => 'courses#index'
  get '/course_search', to: redirect('/courses')
  get '/courses/new', to: redirect('/courses')
  post 'courses' => 'courses#create'
  match '/course_search' => 'courses#course_search', :via => :post
  match '/courses/new' => 'courses#new', :via => :post
  
 
 
  get '/reserved_book', to: redirect('/library')
  get 'library' => 'library#index'
  match '/reserved_book' => 'library#reserved_book', :via => :post

  get 'welcome' => 'welcome#home'

  get '/signup'  => 'users#new'

  get 'admin' => 'users#admin'
  resources :users

  get 'maps/burnaby'
  get 'maps/surrey'
  get 'maps/vancouver'

  resources :maps
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :sessions
  
  resources :messages do
  resources :comments
  resources :users
  end
  
  resources :users do
    resources :courses
  end
  

  get 'transit/index'
  resources :transit

  get '/calendar' => 'calendar#index'
  resources :calendar

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	layout "shoutout"
	before_action :require_user
	before_action :find_message, only: [:show, :edit, :update, :destroy]


	def index
		@message = Message.all.order("created_at DESC")
	end

	def new
		@message = current_user.messages.build
	end

	def show
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to '/messages'
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message.destroy
		redirect_to '/messages'
	end


	private

	def message_params
		params.require(:message).permit(:title, :description)
	end

	def find_message
			@message = Message.find(params[:id])
	end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.erb
<div class="edit_comment">
	<h1 id="editcomment">Edit Message</h1>
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label: "Message" %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>
</div>

app/views/messages/index.html.erb
<% @message.each do |message| %>
	<div class="col-md-4">
		<div class="message">
			<h2 class="message-title"><%= message.title %></h2>
			<%= link_to "View", message, class: "btn-custom" %>
		</div>
	</div>
<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="new_message">
	<h1 class="new-msg-header">Create Message</h1>
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label: "Message Title", class: "title" %>
	<%= f.input :description, class: "input" %>
	<%= f.button :submit, class: "submit_btn" %>
<% end %>
</div>

</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Message by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-desc"><%= @message.description %></p>
	
		<h3 class="comment-section-header">Replies:</h3>
	
		<p><%= render @message.comments %></p>
		<hr>
		<h3 class="reply-to-msg">Reply to Message:</h3>
	
		<%= render 'comments/form' %>


		<div class="links btn-group">
			<%= link_to "Back", '/messages', class: "btn btn-default" %>
			<% if @message.user_id == current_user.id %>
				<%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
				<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>