config/routes.rb
Rails.application.routes.draw do

  

  get 'calendar/index'

  root 'users#index'
  
  
  get 'maps' => 'maps#index'
  
  get '/courses' => 'courses#index'
  get '/course_search', to: redirect('/courses')
  get '/courses/new', to: redirect('/courses')
  post 'courses' => 'courses#create'
  match '/course_search' => 'courses#course_search', :via => :post
  match '/courses/new' => 'courses#new', :via => :post
  
 
 
  get '/reserved_book', to: redirect('/library')
  get 'library' => 'library#index'
  match '/reserved_book' => 'library#reserved_book', :via => :post

  get 'welcome' => 'welcome#home'

  get '/signup'  => 'users#new'

  get 'admin' => 'users#admin'
  resources :users

  get 'maps/burnaby'
  get 'maps/surrey'
  get 'maps/vancouver'

  resources :maps
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :sessions
  
  resources :messages do
  resources :comments
  resources :users
  end
  
  resources :users do
    resources :courses
  end
  

  get 'transit/index'
  resources :transit

  get '/calendar' => 'calendar#index'
  resources :calendar

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_message, only: [:create, :edit, :update, :destroy]
	before_action :find_comment, only: [:edit, :update, :destroy]
	layout 'shoutout'
	def create
		@comment = @message.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to message_path(@message)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to message_path(@message)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to message_path(@message)
	end

	private

		def comment_params
			params.require(:comment).permit(:content)
		end

		def find_message
			@message = Message.find(params[:message_id])
		end

		def find_comment
			@comment = @message.comments.find(params[:id])
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Reply by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
		<% if comment.user_id == current_user.id %>
			<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
			<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
	<%= f.input :content, label: "Comment", :class => "commentbox" %>
	<%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<div class="edit_comment">
<h1 id="editcomment">Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
	<%= f.input :content, label: "Comment" , class: "comment_input" %>
	<%= f.button :submit ,class: "edit_submit_btn" %>
<% end %>
</div>