config/routes.rb
Rails.application.routes.draw do

  

  get 'calendar/index'

  root 'users#index'
  
  
  get 'maps' => 'maps#index'
  
  get '/courses' => 'courses#index'
  get '/course_search', to: redirect('/courses')
  get '/courses/new', to: redirect('/courses')
  post 'courses' => 'courses#create'
  match '/course_search' => 'courses#course_search', :via => :post
  match '/courses/new' => 'courses#new', :via => :post
  
 
 
  get '/reserved_book', to: redirect('/library')
  get 'library' => 'library#index'
  match '/reserved_book' => 'library#reserved_book', :via => :post

  get 'welcome' => 'welcome#home'

  get '/signup'  => 'users#new'

  get 'admin' => 'users#admin'
  resources :users

  get 'maps/burnaby'
  get 'maps/surrey'
  get 'maps/vancouver'

  resources :maps
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :sessions
  
  resources :messages do
  resources :comments
  resources :users
  end
  
  resources :users do
    resources :courses
  end
  

  get 'transit/index'
  resources :transit

  get '/calendar' => 'calendar#index'
  resources :calendar

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<!-- <head>
  <title>Project276</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="header">
  <div class="container">
  <div class="nav pull-right">
  <% if current_user %> 
    <ul> 
      <li><%= current_user.email %></li> 
      <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
      
    </ul> 
  <% else %> 
    <ul> 
      <li><%= link_to "Login", 'login' %></a></li> 
      <li><%= link_to "Signup", 'signup' %></a></li> 
    </ul> 
  <% end %>  
  
  </div>
  </div>
  </div>
  <%= yield %>
</body>
 -->
</html>

app/views/layouts/courses.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Courses</title>
  <%= stylesheet_link_tag    'courses', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

      <a class="navbar-brand" href="/courses">
        Courses
      </a>

      <%= link_to "Home", root_path, :class=>"btn btn-default navbar-btn" %>
      
    </div>
  </div>
</nav>


	
<%= yield %>


</body>
</html>

app/views/layouts/maps.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maps</title>
  <%= stylesheet_link_tag    'maps', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

      <a class="navbar-brand brand_cus" href="/maps">
      Maps
      </a>

    <br>
  <nav>
  <ul class="pagination pagination-lg">
    <li><a href="/maps/burnaby">Burnaby Campus</a></li>
    <li><a href="/maps/surrey">Surrey Campus</a></li>
    <li><a href="/maps/vancouver">Vancouver Campus</a></li>
  </ul>
</nav>
    
    </div>
  </div>
</nav>
	
  <h2>Select a campus to view map</h2>
<%= yield %>

<div id="footer">
  <h3 style="margin-left:5px;"><span class="glyphicon glyphicon-search"></span> Search</h3>
<input type="text" disabled="disabled" class="form-control" style="width:92%;margin-left:15px; float:left;" placeholder="Enter Location">
<button type="submit" disabled="disabled"  style="overflow:hidden; margin-left:5px; margin-right: 5px;" class="btn btn-primary">Go</button>
<br>
<br><br><br>

<hr>
<a href="/welcome"><button type="button" class="btn btn-lg btn-primary">Home</button></a>

</div>
</body>
</html>

app/views/layouts/shoutout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutouts</title>
  <%= stylesheet_link_tag    'custom', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/messages">Shoutouts</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active" style="position:absolute;top:15px;"><%= link_to "Create Message", new_message_path%> <span class="sr-only">(current)</span></a></li>
        
      </ul>
 
      <ul class="nav navbar-nav navbar-right">
       
          
  
            <a href="/welcome"><button type="button" class="btn btn-default navbar-btn">Home</button></a>
 
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

			
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	
<%= yield %>



</body>
</html>

app/views/layouts/transit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transit</title>
  <%= stylesheet_link_tag    'transit', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

      <a class="navbar-brand brand_cus" href="/maps">
      Transit
      </a>

    <br>
  <nav>
  <ul class="pagination pagination-lg">
  	<li><a href='/'><span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span>Home</a></li>
    <li><a href='/transit'>Live Cams</a></li>
    <li><a style="opacity:0.5;pointer-events:none;cursor:default;">Bus Schedules</a></li>
    
  </ul>
</nav>
    
    </div>
  </div>
</nav>

	
<%= yield %>


</body>
</html>